package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"monorepo/apps/gas/graph/model"
)

// SalesSummary is the resolver for the salesSummary field.
func (r *queryResolver) SalesSummary(ctx context.Context, filter *model.SalesFilter, pagination *model.PaginationInput) (*model.SalesSummaryPaginationResponse, error) {
	offset := 0
	limit := 20

	if pagination != nil {
		if pagination.Offset != nil {
			offset = *pagination.Offset
		}
		if pagination.Limit != nil {
			limit = *pagination.Limit
		}
	}

	list, total, err := r.AnalysisService.GetSalesSummary(ctx, filter, offset, limit)
	if err != nil {
		return nil, err
	}

	var result []*model.SalesSummary
	for _, s := range list {
		saleDate := s.SaleDate
		saleMonth := s.SaleMonth
		createdAt := s.CreatedAt
		result = append(result, &model.SalesSummary{
			CreatedAt: &createdAt,
			SaleDate:  &saleDate,
			SaleMonth: &saleMonth,
			SaleYear:  s.SaleYear,
			Quantity:  s.Quantity,
			Total:     s.Total,
		})
	}

	page := (offset / limit) + 1
	hasNext := int64(offset+len(result)) < total

	return &model.SalesSummaryPaginationResponse{
		Data: result,
		Pagination: &model.PageInfo{
			Total:    int(total),
			Page:     page,
			PageSize: limit,
			HasNext:  hasNext,
		},
	}, nil
}

// SalesByDay is the resolver for the salesByDay field.
func (r *queryResolver) SalesByDay(ctx context.Context, filter *model.SalesFilter, pagination *model.PaginationInput) (*model.DailySalesPaginationResponse, error) {
	offset := 0
	limit := 20

	if pagination != nil {
		if pagination.Offset != nil {
			offset = *pagination.Offset
		}
		if pagination.Limit != nil {
			limit = *pagination.Limit
		}
	}

	list, total, err := r.AnalysisService.GetSalesByDay(ctx, filter, offset, limit)
	if err != nil {
		return nil, err
	}

	var result []*model.DailySales
	for _, s := range list {
		result = append(result, &model.DailySales{
			SaleDate: s.SaleDate,
			Quantity: s.Quantity,
			Total:    s.Total,
		})
	}

	page := (offset / limit) + 1
	hasNext := int64(offset+len(result)) < total

	return &model.DailySalesPaginationResponse{
		Data: result,
		Pagination: &model.PageInfo{
			Total:    int(total),
			Page:     page,
			PageSize: limit,
			HasNext:  hasNext,
		},
	}, nil
}

// SalesByMonth is the resolver for the salesByMonth field.
func (r *queryResolver) SalesByMonth(ctx context.Context, filter *model.SalesFilter, pagination *model.PaginationInput) (*model.MonthlySalesPaginationResponse, error) {
	offset := 0
	limit := 20

	if pagination != nil {
		if pagination.Offset != nil {
			offset = *pagination.Offset
		}
		if pagination.Limit != nil {
			limit = *pagination.Limit
		}
	}

	list, total, err := r.AnalysisService.GetSalesByMonth(ctx, filter, offset, limit)
	if err != nil {
		return nil, err
	}

	var result []*model.MonthlySales
	for _, s := range list {
		result = append(result, &model.MonthlySales{
			SaleMonth: s.SaleMonth,
			Quantity:  s.Quantity,
			Total:     s.Total,
		})
	}

	page := (offset / limit) + 1
	hasNext := int64(offset+len(result)) < total

	return &model.MonthlySalesPaginationResponse{
		Data: result,
		Pagination: &model.PageInfo{
			Total:    int(total),
			Page:     page,
			PageSize: limit,
			HasNext:  hasNext,
		},
	}, nil
}

// SalesByYear is the resolver for the salesByYear field.
func (r *queryResolver) SalesByYear(ctx context.Context, filter *model.SalesFilter, pagination *model.PaginationInput) (*model.YearlySalesPaginationResponse, error) {
	offset := 0
	limit := 20

	if pagination != nil {
		if pagination.Offset != nil {
			offset = *pagination.Offset
		}
		if pagination.Limit != nil {
			limit = *pagination.Limit
		}
	}

	list, total, err := r.AnalysisService.GetSalesByYear(ctx, filter, offset, limit)
	if err != nil {
		return nil, err
	}

	var result []*model.YearlySales
	for _, s := range list {
		result = append(result, &model.YearlySales{
			SaleYear: s.SaleYear,
			Quantity: s.Quantity,
			Total:    s.Total,
		})
	}

	page := (offset / limit) + 1
	hasNext := int64(offset+len(result)) < total

	return &model.YearlySalesPaginationResponse{
		Data: result,
		Pagination: &model.PageInfo{
			Total:    int(total),
			Page:     page,
			PageSize: limit,
			HasNext:  hasNext,
		},
	}, nil
}
