package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"monorepo/apps/gas/graph/model"
	"monorepo/shares/entities/mekyra_db"

	"github.com/google/uuid"
)

// CreateDebtTransaction is the resolver for the createDebtTransaction field.
func (r *mutationResolver) CreateDebtTransaction(ctx context.Context, input model.CreateDebtTransactionInput) (*model.DebtTransaction, error) {
	debt := &mekyra_db.Mkrtb_DebtTransaction{
		CustomerId: uuid.MustParse(input.CustomerID),
		Amount:     input.Amount,
		Type:       input.Type,
		Note:       "",
	}
	if input.OrderID != nil {
		oid, _ := uuid.Parse(*input.OrderID)
		debt.OrderId = &oid
	}
	if input.Note != nil {
		debt.Note = *input.Note
	}

	if err := r.DebtService.Create(ctx, debt); err != nil {
		return nil, err
	}

	return r.mapDebtToModel(debt), nil
}

// DeleteDebtTransaction is the resolver for the deleteDebtTransaction field.
func (r *mutationResolver) DeleteDebtTransaction(ctx context.Context, id string) (bool, error) {
	if err := r.DebtService.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// DebtTransactions is the resolver for the debtTransactions field.
func (r *queryResolver) DebtTransactions(ctx context.Context, filter *model.DebtTransactionFilter, pagination *model.PaginationInput) ([]*model.DebtTransaction, error) {
	list := r.DebtService.FindAll(ctx)
	var result []*model.DebtTransaction
	for _, d := range *list {
		result = append(result, r.mapDebtToModel(d))
	}
	return result, nil
}

// DebtTransaction is the resolver for the debtTransaction field.
func (r *queryResolver) DebtTransaction(ctx context.Context, id string) (*model.DebtTransaction, error) {
	d := r.DebtService.FindByID(ctx, id)
	if d == nil || d.Id == uuid.Nil {
		return nil, fmt.Errorf("debt transaction not found")
	}
	return r.mapDebtToModel(d), nil
}
