package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"monorepo/apps/gas/graph/model"
	"monorepo/shares/entities/mekyra_db"

	"github.com/google/uuid"
)

// CreateDelivery is the resolver for the createDelivery field.
func (r *mutationResolver) CreateDelivery(ctx context.Context, input model.CreateDeliveryInput) (*model.Delivery, error) {
	delivery := &mekyra_db.Mkrtb_Delivery{
		OrderId:      uuid.MustParse(input.OrderID),
		DeliveryDate: input.DeliveryDate,
		Status:       "pending",
		Note:         "",
	}
	if input.Note != nil {
		delivery.Note = *input.Note
	}

	if err := r.DeliveryService.Create(ctx, delivery); err != nil {
		return nil, err
	}

	return nil, nil
}

// UpdateDelivery is the resolver for the updateDelivery field.
func (r *mutationResolver) UpdateDelivery(ctx context.Context, id string, input model.UpdateDeliveryInput) (*model.Delivery, error) {
	_, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid delivery ID: %w", err)
	}

	existing := r.DeliveryService.FindByID(ctx, id)
	if existing == nil || existing.Id == uuid.Nil {
		return nil, fmt.Errorf("delivery not found")
	}

	if input.DeliveryDate != nil {
		existing.DeliveryDate = *input.DeliveryDate
	}
	if input.Status != nil {
		existing.Status = *input.Status
	}
	if input.Note != nil {
		existing.Note = *input.Note
	}

	if err := r.DeliveryService.Update(ctx, existing); err != nil {
		return nil, err
	}

	return nil, nil
}

// DeleteDelivery is the resolver for the deleteDelivery field.
func (r *mutationResolver) DeleteDelivery(ctx context.Context, id string) (bool, error) {
	if err := r.DeliveryService.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// Deliveries is the resolver for the deliveries field.
func (r *queryResolver) Deliveries(ctx context.Context, filter *model.DeliveryFilter, pagination *model.PaginationInput) ([]*model.Delivery, error) {
	list := r.DeliveryService.FindAll(ctx)
	var result []*model.Delivery
	for _ = range *list {
		result = append(result, nil)
	}
	return result, nil
}

// Delivery is the resolver for the delivery field.
func (r *queryResolver) Delivery(ctx context.Context, id string) (*model.Delivery, error) {
	d := r.DeliveryService.FindByID(ctx, id)
	if d == nil || d.Id == uuid.Nil {
		return nil, fmt.Errorf("delivery not found")
	}
	return nil, nil
}

// TodayDeliveries is the resolver for the todayDeliveries field.
func (r *queryResolver) TodayDeliveries(ctx context.Context) ([]*model.Delivery, error) {
	list := r.DeliveryService.FindTodayDeliveries(ctx)
	var result []*model.Delivery
	for _ = range *list {
		result = append(result, nil)
	}
	return result, nil
}
