package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"monorepo/apps/gas/graph/model"
	"monorepo/shares/entities/mekyra_db"
	"monorepo/shares/exception"

	"github.com/google/uuid"
)

// CreateInventoryLog is the resolver for the createInventoryLog field.
func (r *mutationResolver) CreateInventoryLog(ctx context.Context, input model.CreateInventoryLogInput) (*model.InventoryLog, error) {
	productID, err := uuid.Parse(input.ProductID)
	if err != nil {
		return nil, &exception.AppError{
			Code:    "INVALID_PRODUCT_ID",
			Message: "ID sản phẩm không hợp lệ",
		}
	}

	log := &mekyra_db.Mkrtb_InventoryLog{
		ProductId: productID,
		Type:      input.Type,
		Quantity:  input.Quantity,
		Note:      "",
	}
	if input.Note != nil {
		log.Note = *input.Note
	}

	if err := r.InventoryService.Create(ctx, log); err != nil {
		return nil, err
	}

	return &model.InventoryLog{
		ID:        log.Id.String(),
		ProductID: log.ProductId.String(),
		Type:      log.Type,
		Quantity:  log.Quantity,
		Note:      &log.Note,
		CreatedAt: &log.CreatedAt,
	}, nil
}

// DeleteInventoryLog is the resolver for the deleteInventoryLog field.
func (r *mutationResolver) DeleteInventoryLog(ctx context.Context, id string) (bool, error) {
	if err := r.InventoryService.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// InventoryLogs is the resolver for the inventoryLogs field.
func (r *queryResolver) InventoryLogs(ctx context.Context, filter *model.InventoryLogFilter, pagination *model.PaginationInput) ([]*model.InventoryLog, error) {
	list := r.InventoryService.FindAll(ctx)
	if list == nil {
		return []*model.InventoryLog{}, nil
	}
	var result []*model.InventoryLog
	for _, l := range *list {
		result = append(result, &model.InventoryLog{
			ID:        l.Id.String(),
			ProductID: l.ProductId.String(),
			Type:      l.Type,
			Quantity:  l.Quantity,
			Note:      &l.Note,
			CreatedAt: &l.CreatedAt,
		})
	}
	return result, nil
}

// InventoryLog is the resolver for the inventoryLog field.
func (r *queryResolver) InventoryLog(ctx context.Context, id string) (*model.InventoryLog, error) {
	l := r.InventoryService.FindByID(ctx, id)
	if l == nil || l.Id == uuid.Nil {
		return nil, fmt.Errorf("inventory log not found")
	}
	return &model.InventoryLog{
		ID:        l.Id.String(),
		ProductID: l.ProductId.String(),
		Type:      l.Type,
		Quantity:  l.Quantity,
		Note:      &l.Note,
		CreatedAt: &l.CreatedAt,
	}, nil
}
