package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"monorepo/apps/gas/graph/model"
)

// CreateMenu is the resolver for the createMenu field.
func (r *mutationResolver) CreateMenu(ctx context.Context, input model.CreateMenuInput) (*model.Menu, error) {
	panic(fmt.Errorf("not implemented: CreateMenu - createMenu"))
}

// UpdateMenu is the resolver for the updateMenu field.
func (r *mutationResolver) UpdateMenu(ctx context.Context, id string, input model.UpdateMenuInput) (*model.Menu, error) {
	panic(fmt.Errorf("not implemented: UpdateMenu - updateMenu"))
}

// DeleteMenu is the resolver for the deleteMenu field.
func (r *mutationResolver) DeleteMenu(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteMenu - deleteMenu"))
}

// Menus is the resolver for the menus field.
func (r *queryResolver) Menus(ctx context.Context) ([]*model.Menu, error) {
	panic(fmt.Errorf("not implemented: Menus - menus"))
}

// Menu is the resolver for the menu field.
func (r *queryResolver) Menu(ctx context.Context, id string) (*model.Menu, error) {
	println("123")
	panic(fmt.Errorf("not implemented: Menu - menu"))
}
