package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"monorepo/apps/gas/graph/model"
	"monorepo/shares/entities/mekyra_db"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.Order, error) {
	order := &mekyra_db.Mkrtb_Order{
		Code:        "",
		TotalAmount: decimal.Zero,
		PaidAmount:  input.PaidAmount,
		DebtAmount:  decimal.Zero,
		Status:      "paid",
		Note:        "",
	}

	if input.CustomerID != nil {
		cid, _ := uuid.Parse(*input.CustomerID)
		order.CustomerId = &cid
	}
	if input.Note != nil {
		order.Note = *input.Note
	}

	var items []*mekyra_db.Mkrtb_OrderItem
	for _, itemInput := range input.Items {
		item := &mekyra_db.Mkrtb_OrderItem{
			ProductId:   uuid.MustParse(itemInput.ProductID),
			Quantity:    itemInput.Quantity,
			Price:       itemInput.Price,
			Total:       itemInput.Price.Mul(decimal.NewFromInt(int64(itemInput.Quantity))),
			ProductName: "",
		}
		items = append(items, item)
		order.TotalAmount = order.TotalAmount.Add(item.Total)
	}

	order.DebtAmount = order.TotalAmount.Sub(order.PaidAmount)
	if order.DebtAmount.GreaterThan(decimal.Zero) {
		order.Status = "debt"
	}

	if err := r.OrderService.Create(ctx, order, items); err != nil {
		return nil, err
	}

	return r.mapOrderToModel(ctx, order), nil
}

// UpdateOrder is the resolver for the updateOrder field.
func (r *mutationResolver) UpdateOrder(ctx context.Context, id string, input model.UpdateOrderInput) (*model.Order, error) {
	_, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid order ID: %w", err)
	}

	existing := r.OrderService.FindByID(ctx, id)
	if existing == nil || existing.Id == uuid.Nil {
		return nil, fmt.Errorf("order not found")
	}

	if input.Status != nil {
		existing.Status = *input.Status
	}
	if input.Note != nil {
		existing.Note = *input.Note
	}

	if err := r.OrderService.Update(ctx, existing); err != nil {
		return nil, err
	}

	return r.mapOrderToModel(ctx, existing), nil
}

// DeleteOrder is the resolver for the deleteOrder field.
func (r *mutationResolver) DeleteOrder(ctx context.Context, id string) (bool, error) {
	if err := r.OrderService.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, filter *model.OrderFilter, pagination *model.PaginationInput) ([]*model.Order, error) {
	list := r.OrderService.FindAll(ctx)
	var result []*model.Order
	for _, o := range *list {
		result = append(result, r.mapOrderToModel(ctx, o))
	}
	return result, nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	o := r.OrderService.FindByID(ctx, id)
	if o == nil || o.Id == uuid.Nil {
		return nil, fmt.Errorf("order not found")
	}
	return r.mapOrderToModel(ctx, o), nil
}

func (r *Resolver) mapOrderToModel(ctx context.Context, o *mekyra_db.Mkrtb_Order) *model.Order {
	var customerID *string
	if o.CustomerId != nil {
		cid := o.CustomerId.String()
		customerID = &cid
	}

	var items []*model.OrderItem
	orderItems := r.OrderService.GetOrderItems(ctx, o.Id.String())
	for _, item := range *orderItems {
		items = append(items, &model.OrderItem{
			ID:          item.Id.String(),
			OrderID:     item.OrderId.String(),
			ProductID:   item.ProductId.String(),
			ProductName: item.ProductName,
			Quantity:    item.Quantity,
			Price:       item.Price,
			Total:       item.Total,
		})
	}

	return &model.Order{
		ID:          o.Id.String(),
		Code:        &o.Code,
		CustomerID:  customerID,
		TotalAmount: o.TotalAmount,
		PaidAmount:  o.PaidAmount,
		DebtAmount:  o.DebtAmount,
		Status:      o.Status,
		Note:        &o.Note,
		Items:       items,
		CreatedAt:   &o.CreatedAt,
	}
}
