package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"monorepo/apps/gas/graph/model"
	"monorepo/shares/entities/mekyra_db"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.Order, error) {
	order := &mekyra_db.Mkrtb_Order{
		Code:        "",
		TotalAmount: decimal.Zero,
		PaidAmount:  input.PaidAmount,
		DebtAmount:  decimal.Zero,
		Status:      "paid",
		Note:        "",
	}

	if input.CustomerID != nil {
		cid, _ := uuid.Parse(*input.CustomerID)
		order.CustomerId = &cid
	}
	if input.Note != nil {
		order.Note = *input.Note
	}

	var items []*mekyra_db.Mkrtb_OrderItem
	for _, itemInput := range input.Items {
		productName := ""
		p := r.ProdService.FindByID(ctx, itemInput.ProductID)
		if p != nil && p.Id != uuid.Nil {
			productName = p.Name
		}

		item := &mekyra_db.Mkrtb_OrderItem{
			ProductId:   uuid.MustParse(itemInput.ProductID),
			Quantity:    itemInput.Quantity,
			Price:       itemInput.Price,
			Total:       itemInput.Price.Mul(decimal.NewFromInt(int64(itemInput.Quantity))),
			ProductName: productName,
		}
		items = append(items, item)
		order.TotalAmount = order.TotalAmount.Add(item.Total)
	}

	order.DebtAmount = order.TotalAmount.Sub(order.PaidAmount)
	if order.DebtAmount.GreaterThan(decimal.Zero) {
		order.Status = "debt"
	}

	if err := r.OrderService.Create(ctx, order, items); err != nil {
		return nil, err
	}

	// Fetch fresh order with items
	createdOrder := r.OrderService.FindByID(ctx, order.Id.String())

	var customerID *string
	if createdOrder.CustomerId != nil {
		cid := createdOrder.CustomerId.String()
		customerID = &cid
	}

	return &model.Order{
		ID:          createdOrder.Id.String(),
		Code:        &createdOrder.Code,
		CustomerID:  customerID,
		TotalAmount: createdOrder.TotalAmount,
		PaidAmount:  createdOrder.PaidAmount,
		DebtAmount:  createdOrder.DebtAmount,
		Status:      createdOrder.Status,
		Note:        &createdOrder.Note,
		CreatedAt:   &createdOrder.CreatedAt,
	}, nil
}

// UpdateOrder is the resolver for the updateOrder field.
func (r *mutationResolver) UpdateOrder(ctx context.Context, id string, input model.UpdateOrderInput) (*model.Order, error) {
	_, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid order ID: %w", err)
	}

	existing := r.OrderService.FindByID(ctx, id)
	if existing == nil || existing.Id == uuid.Nil {
		return nil, fmt.Errorf("order not found")
	}

	if input.Status != nil {
		existing.Status = *input.Status
	}
	if input.Note != nil {
		existing.Note = *input.Note
	}

	if err := r.OrderService.Update(ctx, existing); err != nil {
		return nil, err
	}

	updatedOrder := r.OrderService.FindByID(ctx, id)

	var customerID *string
	if updatedOrder.CustomerId != nil {
		cid := updatedOrder.CustomerId.String()
		customerID = &cid
	}

	return &model.Order{
		ID:          updatedOrder.Id.String(),
		Code:        &updatedOrder.Code,
		CustomerID:  customerID,
		TotalAmount: updatedOrder.TotalAmount,
		PaidAmount:  updatedOrder.PaidAmount,
		DebtAmount:  updatedOrder.DebtAmount,
		Status:      updatedOrder.Status,
		Note:        &updatedOrder.Note,
		CreatedAt:   &updatedOrder.CreatedAt,
	}, nil
}

// DeleteOrder is the resolver for the deleteOrder field.
func (r *mutationResolver) DeleteOrder(ctx context.Context, id string) (bool, error) {
	if err := r.OrderService.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, filter *model.OrderFilter, pagination *model.PaginationInput) (*model.OrderPaginationResponse, error) {
	offset := 0
	limit := 20

	if pagination != nil {
		if pagination.Offset != nil {
			offset = *pagination.Offset
		}
		if pagination.Limit != nil {
			limit = *pagination.Limit
		}
	}

	list, total, err := r.OrderService.FindWithPagination(ctx, filter, offset, limit)
	if err != nil {
		return nil, err
	}

	var result []*model.Order
	for _, o := range list {
		var customerID *string
		var customer *model.Customer
		if o.CustomerId != nil {
			cid := o.CustomerId.String()
			customerID = &cid

			// Fetch customer data
			c := r.CustomerService.FindByID(ctx, cid)
			if c != nil && c.Id != uuid.Nil {
				phone := &c.Phone
				address := &c.Address
				if c.Phone == "" {
					phone = nil
				}
				if c.Address == "" {
					address = nil
				}
				customer = &model.Customer{
					ID:        c.Id.String(),
					Name:      c.Name,
					Phone:     phone,
					Address:   address,
					TotalDebt: c.TotalDebt,
					CreatedAt: &c.CreatedAt,
				}
			}
		}

		var items []*model.OrderItem
		for _, item := range o.Items {
			items = append(items, &model.OrderItem{
				ID:          item.Id.String(),
				OrderID:     item.OrderId.String(),
				ProductID:   item.ProductId.String(),
				ProductName: item.ProductName,
				Quantity:    item.Quantity,
				Price:       item.Price,
				Total:       item.Total,
			})
		}

		result = append(result, &model.Order{
			ID:          o.Id.String(),
			Code:        &o.Code,
			CustomerID:  customerID,
			Customer:    customer,
			TotalAmount: o.TotalAmount,
			PaidAmount:  o.PaidAmount,
			DebtAmount:  o.DebtAmount,
			Status:      o.Status,
			Note:        &o.Note,
			Items:       items,
			CreatedAt:   &o.CreatedAt,
		})
	}

	page := (offset / limit) + 1
	hasNext := int64(offset+len(result)) < total

	return &model.OrderPaginationResponse{
		Data: result,
		Pagination: &model.PageInfo{
			Total:    int(total),
			Page:     page,
			PageSize: limit,
			HasNext:  hasNext,
		},
	}, nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	o := r.OrderService.FindByID(ctx, id)
	if o == nil || o.Id == uuid.Nil {
		return nil, fmt.Errorf("order not found")
	}

	var customerID *string
	var customer *model.Customer
	if o.CustomerId != nil {
		cid := o.CustomerId.String()
		customerID = &cid

		// Fetch customer data
		c := r.CustomerService.FindByID(ctx, cid)
		if c != nil && c.Id != uuid.Nil {
			phone := &c.Phone
			address := &c.Address
			if c.Phone == "" {
				phone = nil
			}
			if c.Address == "" {
				address = nil
			}
			customer = &model.Customer{
				ID:        c.Id.String(),
				Name:      c.Name,
				Phone:     phone,
				Address:   address,
				TotalDebt: c.TotalDebt,
				CreatedAt: &c.CreatedAt,
			}
		}
	}

	var items []*model.OrderItem
	for _, item := range o.Items {
		items = append(items, &model.OrderItem{
			ID:          item.Id.String(),
			OrderID:     item.OrderId.String(),
			ProductID:   item.ProductId.String(),
			ProductName: item.ProductName,
			Quantity:    item.Quantity,
			Price:       item.Price,
			Total:       item.Total,
		})
	}

	return &model.Order{
		ID:          o.Id.String(),
		Code:        &o.Code,
		CustomerID:  customerID,
		Customer:    customer,
		TotalAmount: o.TotalAmount,
		PaidAmount:  o.PaidAmount,
		DebtAmount:  o.DebtAmount,
		Status:      o.Status,
		Note:        &o.Note,
		Items:       items,
		CreatedAt:   &o.CreatedAt,
	}, nil
}

// Items is the resolver for the items field.
func (r *queryResolver) Items(ctx context.Context, orderID string) ([]*model.OrderItem, error) {
	items := r.OrderService.GetOrderItems(ctx, orderID)
	if items == nil {
		return []*model.OrderItem{}, nil
	}

	var result []*model.OrderItem
	for _, item := range *items {
		result = append(result, &model.OrderItem{
			ID:          item.Id.String(),
			OrderID:     item.OrderId.String(),
			ProductID:   item.ProductId.String(),
			ProductName: item.ProductName,
			Quantity:    item.Quantity,
			Price:       item.Price,
			Total:       item.Total,
		})
	}
	return result, nil
}
