package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"monorepo/apps/gas/graph/model"
	"monorepo/shares/entities/mekyra_db"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	product := &mekyra_db.Mkrtb_Product{
		Name:     input.Name,
		Price:    input.Price,
		Category: "",
		Unit:     "",
	}

	if input.Category != nil {
		product.Category = *input.Category
	}
	if input.Unit != nil {
		product.Unit = *input.Unit
	}
	if input.CostPrice != nil {
		product.CostPrice = *input.CostPrice
	}
	if input.StockQuantity != nil {
		product.StockQuantity = *input.StockQuantity
	}
	if input.Barcode != nil {
		product.Barcode = *input.Barcode
	}

	if err := r.ProdService.Create(ctx, product); err != nil {
		return nil, err
	}

	var resultCostPrice *decimal.Decimal
	if !product.CostPrice.IsZero() {
		resultCostPrice = &product.CostPrice
	}

	return &model.Product{
		ID:            product.Id.String(),
		Name:          product.Name,
		Price:         product.Price,
		CostPrice:     resultCostPrice,
		StockQuantity: product.StockQuantity,
		Category:      &product.Category,
		Unit:          &product.Unit,
		Barcode:       &product.Barcode,
	}, nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, input model.UpdateProductInput) (*model.Product, error) {
	_, err := uuid.Parse(input.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid product ID: %w", err)
	}

	existingProduct := r.ProdService.FindByID(ctx, input.ID)
	if existingProduct == nil || existingProduct.Id == uuid.Nil {
		return nil, fmt.Errorf("product not found")
	}

	if input.Name != nil {
		existingProduct.Name = *input.Name
	}
	if input.Price != nil {
		existingProduct.Price = *input.Price
	}
	if input.CostPrice != nil {
		existingProduct.CostPrice = *input.CostPrice
	}
	if input.StockQuantity != nil {
		existingProduct.StockQuantity = *input.StockQuantity
	}
	if input.Category != nil {
		existingProduct.Category = *input.Category
	}
	if input.Unit != nil {
		existingProduct.Unit = *input.Unit
	}
	if input.Barcode != nil {
		existingProduct.Barcode = *input.Barcode
	}

	if err := r.ProdService.Update(ctx, existingProduct); err != nil {
		return nil, err
	}

	var resultCostPrice *decimal.Decimal
	if !existingProduct.CostPrice.IsZero() {
		resultCostPrice = &existingProduct.CostPrice
	}

	return &model.Product{
		ID:            existingProduct.Id.String(),
		Name:          existingProduct.Name,
		Price:         existingProduct.Price,
		CostPrice:     resultCostPrice,
		StockQuantity: existingProduct.StockQuantity,
		Category:      &existingProduct.Category,
		Unit:          &existingProduct.Unit,
		Barcode:       &existingProduct.Barcode,
	}, nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	if err := r.ProdService.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// RestockProduct is the resolver for the restockProduct field.
func (r *mutationResolver) RestockProduct(ctx context.Context, id string, quantity int) (*model.Product, error) {
	productID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid product ID: %w", err)
	}

	existingProduct := r.ProdService.FindByID(ctx, id)
	if existingProduct == nil || existingProduct.Id == uuid.Nil {
		return nil, fmt.Errorf("product not found")
	}

	updatedProduct, err := r.ProdService.Restock(ctx, productID, quantity)
	if err != nil {
		return nil, err
	}

	var resultCostPrice *decimal.Decimal
	if !updatedProduct.CostPrice.IsZero() {
		resultCostPrice = &updatedProduct.CostPrice
	}

	return &model.Product{
		ID:            updatedProduct.Id.String(),
		Name:          updatedProduct.Name,
		Price:         updatedProduct.Price,
		CostPrice:     resultCostPrice,
		StockQuantity: updatedProduct.StockQuantity,
		Category:      &updatedProduct.Category,
		Unit:          &updatedProduct.Unit,
		Barcode:       &updatedProduct.Barcode,
	}, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, filter *model.ProductFilter, pagination *model.PaginationInput) (*model.ProductPaginationResponse, error) {
	offset := 0
	limit := 20

	if pagination != nil {
		if pagination.Offset != nil {
			offset = *pagination.Offset
		}
		if pagination.Limit != nil {
			limit = *pagination.Limit
		}
	}

	list, total, err := r.ProdService.FindWithPagination(ctx, filter, offset, limit)
	if err != nil {
		return nil, err
	}

	var result []*model.Product
	for _, p := range list {
		var costPrice *decimal.Decimal
		if !p.CostPrice.IsZero() {
			costPrice = &p.CostPrice
		}

		result = append(result, &model.Product{
			ID:            p.Id.String(),
			Name:          p.Name,
			Price:         p.Price,
			CostPrice:     costPrice,
			StockQuantity: p.StockQuantity,
			Category:      &p.Category,
			Unit:          &p.Unit,
			Barcode:       &p.Barcode,
		})
	}

	// 👉 tính page từ offset
	pageSize := limit
	page := (offset / limit) + 1
	hasNext := int64(offset+len(result)) < total

	return &model.ProductPaginationResponse{
		Data: result,
		PageInfo: &model.PageInfo{
			Total:    int(total),
			Page:     page,
			PageSize: pageSize,
			HasNext:  hasNext,
		},
	}, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	p := r.ProdService.FindByID(ctx, id)
	if p == nil || p.Id == uuid.Nil {
		return nil, fmt.Errorf("product not found")
	}

	var costPrice *decimal.Decimal
	if !p.CostPrice.IsZero() {
		costPrice = &p.CostPrice
	}

	return &model.Product{
		ID:            p.Id.String(),
		Name:          p.Name,
		Price:         p.Price,
		CostPrice:     costPrice,
		StockQuantity: p.StockQuantity,
		Category:      &p.Category,
		Unit:          &p.Unit,
		Barcode:       &p.Barcode,
	}, nil
}
