package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"monorepo/apps/gas/graph/model"
)

// CreateCustomer is the resolver for the createCustomer field.
func (r *mutationResolver) CreateCustomer(ctx context.Context, input model.CreateCustomerInput) (*model.Customer, error) {
	// TODO: Implement using r.CustomerService
	panic(fmt.Errorf("not implemented: CreateCustomer - createCustomer"))
}

// UpdateCustomer is the resolver for the updateCustomer field.
func (r *mutationResolver) UpdateCustomer(ctx context.Context, id string, input model.UpdateCustomerInput) (*model.Customer, error) {
	// TODO: Implement using r.CustomerService
	panic(fmt.Errorf("not implemented: UpdateCustomer - updateCustomer"))
}

// DeleteCustomer is the resolver for the deleteCustomer field.
func (r *mutationResolver) DeleteCustomer(ctx context.Context, id string) (bool, error) {
	// TODO: Implement using r.CustomerService
	panic(fmt.Errorf("not implemented: DeleteCustomer - deleteCustomer"))
}

// CreateMenu is the resolver for the createMenu field.
func (r *mutationResolver) CreateMenu(ctx context.Context, input model.CreateMenuInput) (*model.Menu, error) {
	// TODO: Implement using r.MenuService
	panic(fmt.Errorf("not implemented: CreateMenu - createMenu"))
}

// UpdateMenu is the resolver for the updateMenu field.
func (r *mutationResolver) UpdateMenu(ctx context.Context, id string, input model.UpdateMenuInput) (*model.Menu, error) {
	// TODO: Implement using r.MenuService
	panic(fmt.Errorf("not implemented: UpdateMenu - updateMenu"))
}

// DeleteMenu is the resolver for the deleteMenu field.
func (r *mutationResolver) DeleteMenu(ctx context.Context, id string) (bool, error) {
	// TODO: Implement using r.MenuService
	panic(fmt.Errorf("not implemented: DeleteMenu - deleteMenu"))
}

// Customers is the resolver for the customers field.
func (r *queryResolver) Customers(ctx context.Context) ([]*model.Customer, error) {
	// TODO: Implement using r.CustomerService
	// Example:
	// customers := r.CustomerService.GetCustomerList()
	// Convert to []*model.Customer and return
	panic(fmt.Errorf("not implemented: Customers - customers"))
}

// Customer is the resolver for the customer field.
func (r *queryResolver) Customer(ctx context.Context, id string) (*model.Customer, error) {
	// TODO: Implement using r.CustomerService
	panic(fmt.Errorf("not implemented: Customer - customer"))
}

// Menus is the resolver for the menus field.
func (r *queryResolver) Menus(ctx context.Context) ([]*model.Menu, error) {
	// TODO: Implement using r.MenuService
	panic(fmt.Errorf("not implemented: Menus - menus"))
}

// Menu is the resolver for the menu field.
func (r *queryResolver) Menu(ctx context.Context, id string) (*model.Menu, error) {
	// Mock implementation - replace with actual service call
	return &model.Menu{
		ID:          id,
		Name:        "Sample Menu",
		Description: strPtr("This is a sample menu"),
		Price:       10.99,
		Category:    strPtr("Food"),
		IsAvailable: true,
	}, nil
}

// Helper function
func strPtr(s string) *string {
	return &s
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
