go:
  port: 8081
database:
  mekyra_db:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: postgres
    dbname: mekyra_db
    sslmode: disable

tenancies:
  mekyra-web: vattumyloc

casdoor:
  organizations:
    mekyra-web:
      server_url: http://localhost:8000
      client_id: 7b2eac2f6418c9b7160e
      client_secret: your-client-secret-here
      organization: mekyra-web
      application: test1
      certificate: |
        -----BEGIN CERTIFICATE-----
        MIIE2TCCAsGgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCYxDjAMBgNVBAoTBWFk
        bWluMRQwEgYDVQQDDAtjZXJ0XzMyNmVkaTAeFw0yNjAzMTcxNjI4MDlaFw00NjAz
        MTcxNjI4MDlaMCYxDjAMBgNVBAoTBWFkbWluMRQwEgYDVQQDDAtjZXJ0XzMyNmVk
        aTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAOJxOWGNM8rkK6MGTtSa
        3ysnVGsNz5xFDdXKfhLLm0dUHPR993q5QrfYuTGJ7Jv8NL+/ldkEdWAiAj2l7FA8
        0FDoxxrYGlCRo+caL7I1XbtplcXch72Vr75Vr09bt9mrBtdfw2zj60kTU+C9r7iQ
        ntLDH/kCZsgRT5oyrCnCtjHmaoJqG2U4m3IhQh2KjQomE5LaU5Pjzh9u0OoFHOrG
        3iukKzXRpQAv4NSpee7VfMrcR9TmmnW7LGiH8+n7Z0t6kgp85qitgla0/nLe74sT
        ia7HkwbaZy9D4Sl1p54Q8e8pDlUPay24wEStP7DnW7UyrkCALr82D7JMTYLf1qCc
        cj1gs3ZLKYchbT3JRIzqqAGdmDS+ta32fBTCJBt6flM1jKgTVAOIfYNBrzO1bCLb
        yFtP7CRsekhTXQSeKBnI33v2cjBVa7GOXSBSRa2fgw07Ww+4L2WObmUo+kgOZG5l
        7TTsTqEjalmT+dsAVAuYE+qE2PuFCptvlSIhlAD7JGgNpyB0Aq/GJ5zJn+R4aGDG
        6hXteqf0IxFkzNWym9B+QoxChRzfRIqekyyp13VntgXuXUCFYM7WVSxkThc9P242
        GQyWW6TvsscHkPisnNVswV/ZT2BEctyMlfCP4aUuqrcWwbFcIQwDbSBkWoQx1dxo
        f1H8fDIuAAZZhBQjFeVsnlr3AgMBAAGjEDAOMAwGA1UdEwEB/wQCMAAwDQYJKoZI
        hvcNAQELBQADggIBAMjhUdV8Myt42av+Y3WA8/Nl0NcYwPJppN1QNV6bwnIq/3Vg
        A5h6zedOR1krCwZN/tKesyT9kz/CC415loVndK2VhiAK4mhek+ooRCT2y9/fL8zn
        HYRdIKRvn8mzpip3aSFd13npKF52j10drOpLVDaReDku7BMLnAKTrwyTchacTSiJ
        fHJFYzrLU/d8V58kfGfBTrP4anf/MN2IO42VFikeDmCKEQUnd8mBXBLh2tkQwS41
        WjX+VUbUNOsQePKXF6868tM1YpJPeI6lfAKxTqMDF6v/G9tensr/4BwxgS/bSoeA
        bKsmfntkco1rZWcReTnV3/q3rRKcUfO6XFnMX4BeOqirKpKECD37jeKJ4R8bqGU0
        WsJZCqegiTFpapVXRytQn9iemWpsweg7JesoX7lBbUwnTnfAcWcvdFDutUT6Sfz6
        qYstJGjNw9chK81QQ8CJ47k+L0PTeWNEcLsuKz2CpixZnAK6jYsZQThjcTx9idIv
        YRMgYagktBrFSvvc+1B8Eikc6ZuJZONVDJdECG885OBVuYD2d1DktWD4lKbjvmPu
        HnqHPUwi8Ey126hLS5mtqf8V2U3GoSDs64mu/cPgE8WbkfgFphUHxCegGczXjhsj
        cB92U0LXM3mRXdhBMGp4u8qJnByi8bn7LiyaoKkCw/Mg1+oJYV/fCnpLa7VS
        -----END CERTIFICATE-----

redis:
  host: localhost:6373
  password: ""
  db: 0