// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

type CreateCustomerInput struct {
	Name    string  `json:"name"`
	Phone   *string `json:"phone,omitempty"`
	Address *string `json:"address,omitempty"`
}

type CreateDebtTransactionInput struct {
	CustomerID string          `json:"customer_id"`
	OrderID    *string         `json:"order_id,omitempty"`
	Amount     decimal.Decimal `json:"amount"`
	Type       string          `json:"type"`
	Note       *string         `json:"note,omitempty"`
}

type CreateDeliveryInput struct {
	OrderID      string    `json:"order_id"`
	DeliveryDate time.Time `json:"delivery_date"`
	Note         *string   `json:"note,omitempty"`
}

type CreateInventoryLogInput struct {
	ProductID string  `json:"product_id"`
	Type      string  `json:"type"`
	Quantity  int     `json:"quantity"`
	Note      *string `json:"note,omitempty"`
}

type CreateMenuInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Price       float64 `json:"price"`
	Category    *string `json:"category,omitempty"`
	IsAvailable *bool   `json:"isAvailable,omitempty"`
}

type CreateOrderInput struct {
	CustomerID *string                 `json:"customer_id,omitempty"`
	Items      []*CreateOrderItemInput `json:"items"`
	PaidAmount decimal.Decimal         `json:"paid_amount"`
	Note       *string                 `json:"note,omitempty"`
}

type CreateOrderItemInput struct {
	ProductID string          `json:"product_id"`
	Quantity  int             `json:"quantity"`
	Price     decimal.Decimal `json:"price"`
}

type CreateProductInput struct {
	Name          string           `json:"name"`
	Category      *string          `json:"category,omitempty"`
	Unit          *string          `json:"unit,omitempty"`
	Price         decimal.Decimal  `json:"price"`
	CostPrice     *decimal.Decimal `json:"cost_price,omitempty"`
	StockQuantity *int             `json:"stock_quantity,omitempty"`
	Barcode       *string          `json:"barcode,omitempty"`
}

type Customer struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Phone     *string         `json:"phone,omitempty"`
	Address   *string         `json:"address,omitempty"`
	TotalDebt decimal.Decimal `json:"total_debt"`
	CreatedAt *time.Time      `json:"created_at,omitempty"`
}

type CustomerFilter struct {
	Search *string `json:"search,omitempty"`
	Phone  *string `json:"phone,omitempty"`
}

type CustomerPaginationResponse struct {
	Data       []*Customer `json:"data"`
	Pagination *PageInfo   `json:"pagination"`
}

type DailySales struct {
	SaleDate time.Time       `json:"sale_date"`
	Quantity int             `json:"quantity"`
	Total    decimal.Decimal `json:"total"`
}

type DailySalesPaginationResponse struct {
	Data       []*DailySales `json:"data"`
	Pagination *PageInfo     `json:"pagination"`
}

type DebtTransaction struct {
	ID         string          `json:"id"`
	CustomerID string          `json:"customer_id"`
	Customer   *Customer       `json:"customer,omitempty"`
	OrderID    *string         `json:"order_id,omitempty"`
	Order      *Order          `json:"order,omitempty"`
	Amount     decimal.Decimal `json:"amount"`
	Type       string          `json:"type"`
	Note       *string         `json:"note,omitempty"`
	CreatedAt  *time.Time      `json:"created_at,omitempty"`
}

type DebtTransactionFilter struct {
	CustomerID *string    `json:"customer_id,omitempty"`
	Type       *string    `json:"type,omitempty"`
	FromDate   *time.Time `json:"from_date,omitempty"`
	ToDate     *time.Time `json:"to_date,omitempty"`
}

type Delivery struct {
	ID           string     `json:"id"`
	OrderID      string     `json:"order_id"`
	Order        *Order     `json:"order,omitempty"`
	DeliveryDate time.Time  `json:"delivery_date"`
	Status       string     `json:"status"`
	Note         *string    `json:"note,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`
}

type DeliveryFilter struct {
	Status       *string    `json:"status,omitempty"`
	DeliveryDate *time.Time `json:"delivery_date,omitempty"`
	FromDate     *time.Time `json:"from_date,omitempty"`
	ToDate       *time.Time `json:"to_date,omitempty"`
}

type InventoryLog struct {
	ID        string     `json:"id"`
	ProductID string     `json:"product_id"`
	Product   *Product   `json:"product,omitempty"`
	Type      string     `json:"type"`
	Quantity  int        `json:"quantity"`
	Note      *string    `json:"note,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

type InventoryLogFilter struct {
	ProductID *string    `json:"product_id,omitempty"`
	Type      *string    `json:"type,omitempty"`
	FromDate  *time.Time `json:"from_date,omitempty"`
	ToDate    *time.Time `json:"to_date,omitempty"`
}

type Menu struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Price       float64 `json:"price"`
	Category    *string `json:"category,omitempty"`
	IsAvailable bool    `json:"isAvailable"`
	CreatedAt   *string `json:"createdAt,omitempty"`
	UpdatedAt   *string `json:"updatedAt,omitempty"`
}

type MonthlySales struct {
	SaleMonth time.Time       `json:"sale_month"`
	Quantity  int             `json:"quantity"`
	Total     decimal.Decimal `json:"total"`
}

type MonthlySalesPaginationResponse struct {
	Data       []*MonthlySales `json:"data"`
	Pagination *PageInfo       `json:"pagination"`
}

type Mutation struct {
}

type Order struct {
	ID          string          `json:"id"`
	Code        *string         `json:"code,omitempty"`
	CustomerID  *string         `json:"customer_id,omitempty"`
	Customer    *Customer       `json:"customer,omitempty"`
	TotalAmount decimal.Decimal `json:"total_amount"`
	PaidAmount  decimal.Decimal `json:"paid_amount"`
	DebtAmount  decimal.Decimal `json:"debt_amount"`
	Status      string          `json:"status"`
	Note        *string         `json:"note,omitempty"`
	Items       []*OrderItem    `json:"items"`
	CreatedAt   *time.Time      `json:"created_at,omitempty"`
}

type OrderFilter struct {
	Status     *string    `json:"status,omitempty"`
	CustomerID *string    `json:"customer_id,omitempty"`
	FromDate   *time.Time `json:"from_date,omitempty"`
	ToDate     *time.Time `json:"to_date,omitempty"`
}

type OrderItem struct {
	ID          string          `json:"id"`
	OrderID     string          `json:"order_id"`
	ProductID   string          `json:"product_id"`
	Product     *Product        `json:"product,omitempty"`
	ProductName string          `json:"product_name"`
	Quantity    int             `json:"quantity"`
	Price       decimal.Decimal `json:"price"`
	Total       decimal.Decimal `json:"total"`
}

type OrderPaginationResponse struct {
	Data       []*Order  `json:"data"`
	Pagination *PageInfo `json:"pagination"`
}

type PageInfo struct {
	Total    int  `json:"total"`
	Page     int  `json:"page"`
	PageSize int  `json:"page_size"`
	HasNext  bool `json:"has_next"`
}

type PaginationInput struct {
	Offset *int `json:"offset,omitempty"`
	Limit  *int `json:"limit,omitempty"`
}

type Product struct {
	ID            string           `json:"id"`
	Name          string           `json:"name"`
	Category      *string          `json:"category,omitempty"`
	Unit          *string          `json:"unit,omitempty"`
	Price         decimal.Decimal  `json:"price"`
	CostPrice     *decimal.Decimal `json:"cost_price,omitempty"`
	StockQuantity int              `json:"stock_quantity"`
	Barcode       *string          `json:"barcode,omitempty"`
	CreatedAt     *time.Time       `json:"created_at,omitempty"`
	UpdatedAt     *time.Time       `json:"updated_at,omitempty"`
	ImgURL        *string          `json:"img_url,omitempty"`
}

type ProductFilter struct {
	Search   *string          `json:"search,omitempty"`
	Barcode  *string          `json:"barcode,omitempty"`
	MinPrice *decimal.Decimal `json:"min_price,omitempty"`
	MaxPrice *decimal.Decimal `json:"max_price,omitempty"`
	Category *string          `json:"category,omitempty"`
}

type ProductPaginationResponse struct {
	Data     []*Product `json:"data,omitempty"`
	PageInfo *PageInfo  `json:"page_info"`
}

type Query struct {
}

type SalesFilter struct {
	FromDate *time.Time `json:"from_date,omitempty"`
	ToDate   *time.Time `json:"to_date,omitempty"`
}

type SalesSummary struct {
	CreatedAt *time.Time      `json:"created_at,omitempty"`
	SaleDate  *time.Time      `json:"sale_date,omitempty"`
	SaleMonth *time.Time      `json:"sale_month,omitempty"`
	SaleYear  int             `json:"sale_year"`
	Quantity  int             `json:"quantity"`
	Total     decimal.Decimal `json:"total"`
}

type SalesSummaryPaginationResponse struct {
	Data       []*SalesSummary `json:"data"`
	Pagination *PageInfo       `json:"pagination"`
}

type UpdateCustomerInput struct {
	Name    *string `json:"name,omitempty"`
	Phone   *string `json:"phone,omitempty"`
	Address *string `json:"address,omitempty"`
}

type UpdateDeliveryInput struct {
	DeliveryDate *time.Time `json:"delivery_date,omitempty"`
	Status       *string    `json:"status,omitempty"`
	Note         *string    `json:"note,omitempty"`
}

type UpdateMenuInput struct {
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	Price       *float64 `json:"price,omitempty"`
	Category    *string  `json:"category,omitempty"`
	IsAvailable *bool    `json:"isAvailable,omitempty"`
}

type UpdateOrderInput struct {
	Status *string `json:"status,omitempty"`
	Note   *string `json:"note,omitempty"`
}

type UpdateProductInput struct {
	ID            string           `json:"id"`
	Name          *string          `json:"name,omitempty"`
	Category      *string          `json:"category,omitempty"`
	Unit          *string          `json:"unit,omitempty"`
	Price         *decimal.Decimal `json:"price,omitempty"`
	CostPrice     *decimal.Decimal `json:"cost_price,omitempty"`
	StockQuantity *int             `json:"stock_quantity,omitempty"`
	Barcode       *string          `json:"barcode,omitempty"`
}

type YearlySales struct {
	SaleYear int             `json:"sale_year"`
	Quantity int             `json:"quantity"`
	Total    decimal.Decimal `json:"total"`
}

type YearlySalesPaginationResponse struct {
	Data       []*YearlySales `json:"data"`
	Pagination *PageInfo      `json:"pagination"`
}
