// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateCustomerInput struct {
	Name    string  `json:"name"`
	Email   string  `json:"email"`
	Phone   *string `json:"phone,omitempty"`
	Address *string `json:"address,omitempty"`
}

type CreateMenuInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Price       float64 `json:"price"`
	Category    *string `json:"category,omitempty"`
	IsAvailable *bool   `json:"isAvailable,omitempty"`
}

type CreateProductInput struct {
	Name          string   `json:"name"`
	Category      *string  `json:"category,omitempty"`
	Unit          *string  `json:"unit,omitempty"`
	Price         float64  `json:"price"`
	CostPrice     *float64 `json:"cost_price,omitempty"`
	StockQuantity *int     `json:"stock_quantity,omitempty"`
	Barcode       *string  `json:"barcode,omitempty"`
}

type Customer struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	Phone     *string `json:"phone,omitempty"`
	Address   *string `json:"address,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type Menu struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Price       float64 `json:"price"`
	Category    *string `json:"category,omitempty"`
	IsAvailable bool    `json:"isAvailable"`
	CreatedAt   *string `json:"createdAt,omitempty"`
	UpdatedAt   *string `json:"updatedAt,omitempty"`
}

type Mutation struct {
}

type PaginationInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type Product struct {
	ID            string     `json:"id"`
	Name          string     `json:"name"`
	Category      *string    `json:"category,omitempty"`
	Unit          *string    `json:"unit,omitempty"`
	Price         float64    `json:"price"`
	CostPrice     *float64   `json:"cost_price,omitempty"`
	StockQuantity int        `json:"stock_quantity"`
	Barcode       *string    `json:"barcode,omitempty"`
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	UpdatedAt     *time.Time `json:"updated_at,omitempty"`
}

type ProductFilter struct {
	Search   *string  `json:"search,omitempty"`
	Barcode  *string  `json:"barcode,omitempty"`
	MinPrice *float64 `json:"min_price,omitempty"`
	MaxPrice *float64 `json:"max_price,omitempty"`
	Category *string  `json:"category,omitempty"`
}

type Query struct {
}

type UpdateCustomerInput struct {
	Name    *string `json:"name,omitempty"`
	Email   *string `json:"email,omitempty"`
	Phone   *string `json:"phone,omitempty"`
	Address *string `json:"address,omitempty"`
}

type UpdateMenuInput struct {
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	Price       *float64 `json:"price,omitempty"`
	Category    *string  `json:"category,omitempty"`
	IsAvailable *bool    `json:"isAvailable,omitempty"`
}

type UpdateProductInput struct {
	ID            string   `json:"id"`
	Name          *string  `json:"name,omitempty"`
	Category      *string  `json:"category,omitempty"`
	Unit          *string  `json:"unit,omitempty"`
	Price         *float64 `json:"price,omitempty"`
	CostPrice     *float64 `json:"cost_price,omitempty"`
	StockQuantity *int     `json:"stock_quantity,omitempty"`
	Barcode       *string  `json:"barcode,omitempty"`
}
